apiVersion: azure.upbound.io/v1beta1
metadata:
  name: azure-provider-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/depends-on: provider-azure-management
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: azure-secret
      key: creds