apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: aks-dev
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: azure-provider-config
  forProvider:    
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D2_v2
        vnetSubnetIdRef:
          name: sub-dev
    dnsPrefix: ${{ values.dnsPrefix }}
    identity:
      - type: SystemAssigned
    location: ${{ values.region }}
    resourceGroupNameRef:
      name: ${{ values.resourceGroupName }}