apiVersion: compositions.io/v1alpha1
kind: XCluster
metadata:
  name: ${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: azure-provider-config  # Propagate the providerConfigRef here
  parameters:
    clusterName: ${{ values.clusterName }}
    region: ${{ values.region }}
    resourceGroupName: ${{ values.resourceGroupName }}
    kubernetesVersion: ${{ values.kubernetesVersion }}
    dnsPrefix: ${{ values.dnsPrefix }}
    agentPoolProfiles: ${{ values.agentPoolProfiles }}
  compositionRef:
    name: aks-cluster-nodepool