apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aks-cluster-nodepool
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  compositeTypeRef:
    apiVersion: compositions.io/v1alpha1
    kind: XCluster
  resources:
    - name: cluster
      base:
        apiVersion:  containerservice.azure.upbound.io/v1beta1
        kind: KubernetesCluster
        metadata:
          labels:
            cluster_name: ${{ values.clusterName }}
        spec:
          providerConfigRef:
            name: azure-provider-config  # Propagate the providerConfigRef here
          forProvider:    
            defaultNodePool:
              - name: default
                nodeCount: 1
                vmSize: Standard_D2_v2           
            dnsPrefix: ${{ values.dnsPrefix }}
            identity:
              - type: SystemAssigned
            location: ${{ values.region }}
            resourceGroupNameRef:
              name: rg-aks         
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.clusterName"
          toFieldPath: "metadata.labels.cluster_name"

    - name: rg-aks
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        metadata:
          name: ${{ values.resourceGroupName }}
        spec:
          providerConfigRef:
            name: azure-provider-config  # This line points to your specific ProviderConfig
          forProvider:
            location: ${{ values.region }}
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.region"
          toFieldPath: "spec.forProvider.location"

    - name: NodePool
      base:
        apiVersion: containerservice.azure.upbound.io/v1beta1
        kind: KubernetesClusterNodePool
        metadata:
          labels:
            name: ${{ values.agentPoolProfiles[0].name }}
        spec:
          forProvider:
            nodeCount: ${{ values.agentPoolProfiles[0].nodeCount }}
            vmSize: ${{ values.agentPoolProfiles[0].vmSize }}
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.agentPoolProfiles[0].name"
          toFieldPath: "metadata.labels.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.agentPoolProfiles[0].nodeCount"
          toFieldPath: "spec.forProvider.nodeCount"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.parameters.agentPoolProfiles[0].vmSize"
          toFieldPath: "spec.forProvider.vmSize"