apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: sub-${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: azure-provider-config
  forProvider:
    addressPrefixes:
      - 10.2.0.0/24
    resourceGroupNameRef:
      name: ${{ values.resourceGroupName }}
    virtualNetworkNameRef:
      name: vn-${{ values.clusterName }}
  writeConnectionSecretToRef:
    name: ${{ values.clusterName }}-azure-connection-secret
    namespace: upbound-system