apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: vn-dev
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  providerConfigRef:
    name: azure-provider-config
  forProvider:
    resourceGroupNameRef:
      name: ${{ values.resourceGroupName }}
    location: ${{ values.region }}
    addressSpace:
      - 10.2.0.0/16
  writeConnectionSecretToRef:
    name: ${{ values.clusterName }}-azure-connection-secret
    namespace: upbound-system